package negocios;

public class CarrinhoDePedidos {

	// NA INTERFACE, O FUNCIONÁRIO VAI FAZER DE ALGUMA FORMA A AÇÃO DE CRIAR UMA
	// NOVA VENDA, NISSO ELE VAI GERAR UM NOVO CARRINHO DE PEDIDOS PARA UM
	// DETERMINADO CLIENTE.
	// CONTER-> CLIENTE ESPECÍFICO RELACIONADO, FUNCIONÁRIO ESPECÍFICO RELACIONADO
	// ,ARRAY LIST DE PRODUTOS, QUANTIDADE DE CADA PRODUTO FEITO NO PEDIDO,
	// E O PEDIDO EM
	// SI.

}
