package negocios;

public class ControladorProduto {

	// AQUI VAI SER O CARDÁPIO EM SI, BASICAMENTE CONTROLAR SE O PRODUTO TEM
	// ESTOQUE.
	// CONTROLA PRODUTOS QUE JÁ EXISTEM, NÃO CADASTRA NADA!!!
	// IMPORTA O CADASTRO DE PRODUTOS E ADICIONA NOVOS MECANISMOS.

}
